### ISSUE TITLE
F keys not working in some terminals

### ISSUE THREAD

**Issue by sysadminmike** [jrmarino/Slider#1]
If i login and use slider directly on the machines console all is ok 
however if i try to use it from a login via ssh from another machine slider loads however the F keys do not work so its not possible to use most of it
F keys do register on console eg if i press F4 
   #4~
   4~: not found

**Comment by jrmarino** [comment]
what happens if you set environment variable TERM to "xterm"  first?

maybe I'll make 1,2,3,4 do the same thing as F1,F2,F3,F4 on the next edition.

**Comment by sysadminmike** [comment]
Just tested with no luck:

 # setenv TERM xterm
 # env | grep term
 TERM=xterm

**Comment by jrmarino** [comment]
hmm.   the terminal emulator you are using seems not to be supported but xterm should be supported.  maybe its stuck on cons25.
"env TERM=xterm slider" doesn't work either?

also, i am not sure what ssh program you are using, but sometimes you can set the terminal emulator there.

**Comment by sysadminmike** [comment]
Just tried by setting env from the machine im running ssh from:

env TERM=xterm ssh -l mike dragonflybox

but still not working im afraid.  

If you can make 1234 do the same things on the next release that would be great.

btw - I have just done a quick test in nano and F1 is working and brings up the help page so the F keys are working

**Comment by jrmarino** [comment]
hi mike,
I pushed a new slider if you want to build it from source (it's in dports now but not packages yet)  

I also found a pretty big bug in the "scan directory for deleted files" functionality, which I was able to fix, so everyone will want the latest version (2.06).

John

**Comment by sysadminmike** [comment]
just updated my dports and installed 2.06 - thanks 1234 work in the ssh term.
